volumes:
  pg_data:

services:
  db:
    container_name: bot_car_number_db
    image: ${DB_IMAGE}
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
  
  redis:
    container_name: auto_redis
    image: ${REDIS_IMAGE}
    restart: on-failure

  bot:
    container_name: bot_car_number
    image: ${BOT_IMAGE}
    env_file: .env
    depends_on:
      - db
      - redis
    command: sh -c "sleep 10 && alembic upgrade head && python -m app"
    restart: on-failure