version: "3"

volumes:
  pg_data:

services:
  db:
    container_name: auto_db
    image: ${DB_IMAGE}
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  bot:
    container_name: auto_bot
    image: ${BOT_IMAGE}
    env_file: .env
    depends_on:
      - db
    command: sh -c "sleep 10 && alembic upgrade head && python -m app"
    restart: always